
// This file has been generated by the GUI designer. Do not modify.
namespace MeeGen
{
	public partial class InfoDialog
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label3;

		private global::Gtk.Image image7;

		private global::Gtk.Label label1;

		private global::Gtk.Button button109;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MeeGen.InfoDialog
			this.Name = "MeeGen.InfoDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Info");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.logo2.svg");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			// Internal child MeeGen.InfoDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("MeeGen#");
			this.label3.Angle = 360;
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image ();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.logo2.svg");
			this.vbox2.Add (this.image7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image7]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Check the source code (InfoDialog.cs) \nto see the text that is actually being displayed.");
			this.label1.UseMarkup = true;
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Internal child MeeGen.InfoDialog.ActionArea
			global::Gtk.HButtonBox w6 = this.ActionArea;
			w6.Name = "__gtksharp_78_Stetic_TopLevelDialog_ActionArea";
			w6.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child __gtksharp_78_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button109 = new global::Gtk.Button ();
			this.button109.CanFocus = true;
			this.button109.Name = "button109";
			this.button109.UseUnderline = true;
			this.button109.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button109.Label = global::Mono.Unix.Catalog.GetString ("_Close");
			this.AddActionWidget (this.button109, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w6[this.button109]));
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 331;
			this.DefaultHeight = 305;
			this.Show ();
			this.button109.Clicked += new global::System.EventHandler (this.CloseClicked);
		}
	}
}
