
// This file has been generated by the GUI designer. Do not modify.
namespace MeeGen
{
	public partial class MainWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.VButtonBox vbuttonbox1;

		private global::Gtk.Button BtnHeads;

		private global::Gtk.Button BtnHair;

		private global::Gtk.Button BtnArms;

		private global::Gtk.Button BtnBodies;

		private global::Gtk.Button BtnLegs;

		private global::Gtk.Button BtnPets;

		private global::Gtk.Button BtnItems;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label1;

		private global::Gtk.Image image8;

		private global::Gtk.Table table1;

		private global::Gtk.Button BtnAbout;

		private global::Gtk.Button BtnReset;

		private global::Gtk.Button button14;

		private global::Gtk.Button button17;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HButtonBox hbuttonbox15;

		private global::Gtk.Button BtnZoomIn;

		private global::Gtk.Button BtnZoomOut;

		private global::Gtk.Button BtnRotateLeft;

		private global::Gtk.Button BtnRotateRight;

		private global::Gtk.Button BtnFlip;

		private global::Gtk.Button BtnColorSelection;

		private global::Gtk.DrawingArea drawingarea;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button BtnScrollLeft;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.IconView iconview;

		private global::Gtk.Button BtnScrollRight;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MeeGen.MainWindow
			this.Name = "MeeGen.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MeeGen#");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.logo2.svg");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowShrink = true;
			// Container child MeeGen.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnHeads = new global::Gtk.Button ();
			this.BtnHeads.CanFocus = true;
			this.BtnHeads.Name = "BtnHeads";
			this.BtnHeads.UseUnderline = true;
			this.BtnHeads.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnHeads.Label = global::Mono.Unix.Catalog.GetString ("Heads");
			this.vbuttonbox1.Add (this.BtnHeads);
			global::Gtk.ButtonBox.ButtonBoxChild w1 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnHeads]));
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnHair = new global::Gtk.Button ();
			this.BtnHair.CanFocus = true;
			this.BtnHair.Name = "BtnHair";
			this.BtnHair.UseUnderline = true;
			this.BtnHair.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnHair.Label = global::Mono.Unix.Catalog.GetString ("Hair");
			this.vbuttonbox1.Add (this.BtnHair);
			global::Gtk.ButtonBox.ButtonBoxChild w2 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnHair]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnArms = new global::Gtk.Button ();
			this.BtnArms.CanFocus = true;
			this.BtnArms.Name = "BtnArms";
			this.BtnArms.UseUnderline = true;
			this.BtnArms.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnArms.Label = global::Mono.Unix.Catalog.GetString ("Arms");
			this.vbuttonbox1.Add (this.BtnArms);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnArms]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnBodies = new global::Gtk.Button ();
			this.BtnBodies.CanFocus = true;
			this.BtnBodies.Name = "BtnBodies";
			this.BtnBodies.UseUnderline = true;
			this.BtnBodies.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnBodies.Label = global::Mono.Unix.Catalog.GetString ("Bodies");
			this.vbuttonbox1.Add (this.BtnBodies);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnBodies]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnLegs = new global::Gtk.Button ();
			this.BtnLegs.CanFocus = true;
			this.BtnLegs.Name = "BtnLegs";
			this.BtnLegs.UseUnderline = true;
			this.BtnLegs.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnLegs.Label = global::Mono.Unix.Catalog.GetString ("Legs");
			this.vbuttonbox1.Add (this.BtnLegs);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnLegs]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnPets = new global::Gtk.Button ();
			this.BtnPets.CanFocus = true;
			this.BtnPets.Name = "BtnPets";
			this.BtnPets.UseUnderline = true;
			this.BtnPets.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnPets.Label = global::Mono.Unix.Catalog.GetString ("Pets");
			this.vbuttonbox1.Add (this.BtnPets);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnPets]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.BtnItems = new global::Gtk.Button ();
			this.BtnItems.CanFocus = true;
			this.BtnItems.Name = "BtnItems";
			this.BtnItems.Relief = ((global::Gtk.ReliefStyle)(2));
			this.BtnItems.Xalign = 0f;
			this.BtnItems.Yalign = 0f;
			this.BtnItems.BorderWidth = ((uint)(8));
			// Container child BtnItems.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			this.hbox2.BorderWidth = ((uint)(5));
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Items");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.label1.WidthChars = 8;
			this.label1.SingleLineMode = true;
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.image8 = new global::Gtk.Image ();
			this.image8.Name = "image8";
			this.image8.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.small-arrow-right.png");
			this.hbox2.Add (this.image8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.image8]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.BtnItems.Add (this.hbox2);
			this.BtnItems.Label = null;
			this.vbuttonbox1.Add (this.BtnItems);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1[this.BtnItems]));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox2.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbuttonbox1]));
			w11.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), true);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(5));
			this.table1.ColumnSpacing = ((uint)(20));
			this.table1.BorderWidth = ((uint)(5));
			// Container child table1.Gtk.Table+TableChild
			this.BtnAbout = new global::Gtk.Button ();
			this.BtnAbout.TooltipMarkup = "About";
			this.BtnAbout.CanFocus = true;
			this.BtnAbout.Name = "BtnAbout";
			this.BtnAbout.UseUnderline = true;
			this.BtnAbout.FocusOnClick = false;
			this.BtnAbout.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnAbout.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.dialog-information.png");
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w13.Add (w16);
			w12.Add (w13);
			this.BtnAbout.Add (w12);
			this.table1.Add (this.BtnAbout);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnAbout]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.BtnReset = new global::Gtk.Button ();
			this.BtnReset.TooltipMarkup = "Reset";
			this.BtnReset.CanFocus = true;
			this.BtnReset.Name = "BtnReset";
			this.BtnReset.UseUnderline = true;
			this.BtnReset.FocusOnClick = false;
			this.BtnReset.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnReset.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.user-trash.png");
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w22.Add (w25);
			w21.Add (w22);
			this.BtnReset.Add (w21);
			this.table1.Add (this.BtnReset);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1[this.BtnReset]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button14 = new global::Gtk.Button ();
			this.button14.TooltipMarkup = "Export";
			this.button14.CanFocus = true;
			this.button14.Name = "button14";
			this.button14.UseUnderline = true;
			this.button14.FocusOnClick = false;
			this.button14.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child button14.Gtk.Container+ContainerChild
			global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w31 = new global::Gtk.HBox ();
			w31.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.document-save.png");
			w31.Add (w32);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w34 = new global::Gtk.Label ();
			w31.Add (w34);
			w30.Add (w31);
			this.button14.Add (w30);
			this.table1.Add (this.button14);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1[this.button14]));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.button17 = new global::Gtk.Button ();
			this.button17.TooltipMarkup = "Sync";
			this.button17.CanFocus = true;
			this.button17.Name = "button17";
			this.button17.UseUnderline = true;
			this.button17.FocusOnClick = false;
			this.button17.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child button17.Gtk.Container+ContainerChild
			global::Gtk.Alignment w39 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w40 = new global::Gtk.HBox ();
			w40.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w41 = new global::Gtk.Image ();
			w41.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.folder-remote.png");
			w40.Add (w41);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w43 = new global::Gtk.Label ();
			w40.Add (w43);
			w39.Add (w40);
			this.button17.Add (w39);
			this.table1.Add (this.button17);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1[this.button17]));
			w47.LeftAttach = ((uint)(1));
			w47.RightAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbuttonbox15 = new global::Gtk.HButtonBox ();
			this.hbuttonbox15.Name = "hbuttonbox15";
			this.hbuttonbox15.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(2));
			// Container child hbuttonbox15.Gtk.ButtonBox+ButtonBoxChild
			this.BtnZoomIn = new global::Gtk.Button ();
			this.BtnZoomIn.CanFocus = true;
			this.BtnZoomIn.Name = "BtnZoomIn";
			this.BtnZoomIn.UseUnderline = true;
			this.BtnZoomIn.FocusOnClick = false;
			this.BtnZoomIn.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnZoomIn.Gtk.Container+ContainerChild
			global::Gtk.Alignment w50 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w51 = new global::Gtk.HBox ();
			w51.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w52 = new global::Gtk.Image ();
			w52.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.zoom-in.png");
			w51.Add (w52);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w54 = new global::Gtk.Label ();
			w51.Add (w54);
			w50.Add (w51);
			this.BtnZoomIn.Add (w50);
			this.hbuttonbox15.Add (this.BtnZoomIn);
			global::Gtk.ButtonBox.ButtonBoxChild w58 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox15[this.BtnZoomIn]));
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbuttonbox15.Gtk.ButtonBox+ButtonBoxChild
			this.BtnZoomOut = new global::Gtk.Button ();
			this.BtnZoomOut.CanFocus = true;
			this.BtnZoomOut.Name = "BtnZoomOut";
			this.BtnZoomOut.UseUnderline = true;
			this.BtnZoomOut.FocusOnClick = false;
			this.BtnZoomOut.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnZoomOut.Gtk.Container+ContainerChild
			global::Gtk.Alignment w59 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w60 = new global::Gtk.HBox ();
			w60.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w61 = new global::Gtk.Image ();
			w61.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.zoom-out.png");
			w60.Add (w61);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w63 = new global::Gtk.Label ();
			w60.Add (w63);
			w59.Add (w60);
			this.BtnZoomOut.Add (w59);
			this.hbuttonbox15.Add (this.BtnZoomOut);
			global::Gtk.ButtonBox.ButtonBoxChild w67 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox15[this.BtnZoomOut]));
			w67.Position = 1;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbuttonbox15.Gtk.ButtonBox+ButtonBoxChild
			this.BtnRotateLeft = new global::Gtk.Button ();
			this.BtnRotateLeft.CanFocus = true;
			this.BtnRotateLeft.Name = "BtnRotateLeft";
			this.BtnRotateLeft.UseUnderline = true;
			this.BtnRotateLeft.FocusOnClick = false;
			this.BtnRotateLeft.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnRotateLeft.Gtk.Container+ContainerChild
			global::Gtk.Alignment w68 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w69 = new global::Gtk.HBox ();
			w69.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w70 = new global::Gtk.Image ();
			w70.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.object-rotate-left.png");
			w69.Add (w70);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w72 = new global::Gtk.Label ();
			w69.Add (w72);
			w68.Add (w69);
			this.BtnRotateLeft.Add (w68);
			this.hbuttonbox15.Add (this.BtnRotateLeft);
			global::Gtk.ButtonBox.ButtonBoxChild w76 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox15[this.BtnRotateLeft]));
			w76.Position = 2;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbuttonbox15.Gtk.ButtonBox+ButtonBoxChild
			this.BtnRotateRight = new global::Gtk.Button ();
			this.BtnRotateRight.CanFocus = true;
			this.BtnRotateRight.Name = "BtnRotateRight";
			this.BtnRotateRight.UseUnderline = true;
			this.BtnRotateRight.FocusOnClick = false;
			this.BtnRotateRight.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnRotateRight.Gtk.Container+ContainerChild
			global::Gtk.Alignment w77 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w78 = new global::Gtk.HBox ();
			w78.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w79 = new global::Gtk.Image ();
			w79.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.object-rotate-right.png");
			w78.Add (w79);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w81 = new global::Gtk.Label ();
			w78.Add (w81);
			w77.Add (w78);
			this.BtnRotateRight.Add (w77);
			this.hbuttonbox15.Add (this.BtnRotateRight);
			global::Gtk.ButtonBox.ButtonBoxChild w85 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox15[this.BtnRotateRight]));
			w85.Position = 3;
			w85.Expand = false;
			w85.Fill = false;
			// Container child hbuttonbox15.Gtk.ButtonBox+ButtonBoxChild
			this.BtnFlip = new global::Gtk.Button ();
			this.BtnFlip.CanFocus = true;
			this.BtnFlip.Name = "BtnFlip";
			this.BtnFlip.UseUnderline = true;
			this.BtnFlip.FocusOnClick = false;
			this.BtnFlip.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnFlip.Gtk.Container+ContainerChild
			global::Gtk.Alignment w86 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w87 = new global::Gtk.HBox ();
			w87.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w88 = new global::Gtk.Image ();
			w88.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.object-flip-horizontal.png");
			w87.Add (w88);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w90 = new global::Gtk.Label ();
			w87.Add (w90);
			w86.Add (w87);
			this.BtnFlip.Add (w86);
			this.hbuttonbox15.Add (this.BtnFlip);
			global::Gtk.ButtonBox.ButtonBoxChild w94 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox15[this.BtnFlip]));
			w94.Position = 4;
			w94.Expand = false;
			w94.Fill = false;
			// Container child hbuttonbox15.Gtk.ButtonBox+ButtonBoxChild
			this.BtnColorSelection = new global::Gtk.Button ();
			this.BtnColorSelection.CanFocus = true;
			this.BtnColorSelection.Name = "BtnColorSelection";
			this.BtnColorSelection.UseUnderline = true;
			this.BtnColorSelection.FocusOnClick = false;
			this.BtnColorSelection.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnColorSelection.Gtk.Container+ContainerChild
			global::Gtk.Alignment w95 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w96 = new global::Gtk.HBox ();
			w96.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w97 = new global::Gtk.Image ();
			w97.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.color-chooser.png");
			w96.Add (w97);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w99 = new global::Gtk.Label ();
			w96.Add (w99);
			w95.Add (w96);
			this.BtnColorSelection.Add (w95);
			this.hbuttonbox15.Add (this.BtnColorSelection);
			global::Gtk.ButtonBox.ButtonBoxChild w103 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox15[this.BtnColorSelection]));
			w103.Position = 5;
			w103.Expand = false;
			w103.Fill = false;
			this.vbox6.Add (this.hbuttonbox15);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbuttonbox15]));
			w104.Position = 0;
			w104.Expand = false;
			w104.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.drawingarea = new global::Gtk.DrawingArea ();
			this.drawingarea.Events = ((global::Gdk.EventMask)(768));
			this.drawingarea.Name = "drawingarea";
			this.vbox6.Add (this.drawingarea);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.drawingarea]));
			w105.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.BtnScrollLeft = new global::Gtk.Button ();
			this.BtnScrollLeft.CanFocus = true;
			this.BtnScrollLeft.Name = "BtnScrollLeft";
			this.BtnScrollLeft.UseUnderline = true;
			this.BtnScrollLeft.FocusOnClick = false;
			this.BtnScrollLeft.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnScrollLeft.Gtk.Container+ContainerChild
			global::Gtk.Alignment w106 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w107 = new global::Gtk.HBox ();
			w107.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w108 = new global::Gtk.Image ();
			w108.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.arrow-left.png");
			w107.Add (w108);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w110 = new global::Gtk.Label ();
			w107.Add (w110);
			w106.Add (w107);
			this.BtnScrollLeft.Add (w106);
			this.hbox4.Add (this.BtnScrollLeft);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.BtnScrollLeft]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.iconview = new global::Gtk.IconView ();
			this.iconview.CanFocus = true;
			this.iconview.Name = "iconview";
			this.GtkScrolledWindow.Add (this.iconview);
			this.hbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GtkScrolledWindow]));
			w116.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.BtnScrollRight = new global::Gtk.Button ();
			this.BtnScrollRight.CanFocus = true;
			this.BtnScrollRight.Name = "BtnScrollRight";
			this.BtnScrollRight.UseUnderline = true;
			this.BtnScrollRight.FocusOnClick = false;
			this.BtnScrollRight.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child BtnScrollRight.Gtk.Container+ContainerChild
			global::Gtk.Alignment w117 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w118 = new global::Gtk.HBox ();
			w118.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w119 = new global::Gtk.Image ();
			w119.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("MeeGen.Resources.arrow-right.png");
			w118.Add (w119);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w121 = new global::Gtk.Label ();
			w118.Add (w121);
			w117.Add (w118);
			this.BtnScrollRight.Add (w117);
			this.hbox4.Add (this.BtnScrollRight);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.BtnScrollRight]));
			w125.Position = 2;
			w125.Expand = false;
			w125.Fill = false;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w126.Position = 2;
			w126.Expand = false;
			w126.Fill = false;
			this.hbox1.Add (this.vbox6);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox6]));
			w127.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w128.Position = 0;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 791;
			this.DefaultHeight = 551;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.BtnHeads.Clicked += new global::System.EventHandler (this.CategoryButtonClicked);
			this.BtnHair.Clicked += new global::System.EventHandler (this.CategoryButtonClicked);
			this.BtnArms.Clicked += new global::System.EventHandler (this.CategoryButtonClicked);
			this.BtnBodies.Clicked += new global::System.EventHandler (this.CategoryButtonClicked);
			this.BtnLegs.Clicked += new global::System.EventHandler (this.CategoryButtonClicked);
			this.BtnPets.Clicked += new global::System.EventHandler (this.CategoryButtonClicked);
			this.BtnItems.Clicked += new global::System.EventHandler (this.ItemsButtonClicked);
			this.button17.Clicked += new global::System.EventHandler (this.SyncButtonClicked);
			this.button14.Clicked += new global::System.EventHandler (this.ExportButtonClicked);
			this.BtnReset.Clicked += new global::System.EventHandler (this.ResetButtonClicked);
			this.BtnAbout.Clicked += new global::System.EventHandler (this.AboutButtonClicked);
			this.BtnZoomIn.Clicked += new global::System.EventHandler (this.ZoomInButtonClicked);
			this.BtnZoomOut.Clicked += new global::System.EventHandler (this.ZoomOutButtonClicked);
			this.BtnRotateLeft.Clicked += new global::System.EventHandler (this.RotateLeftButtonClicked);
			this.BtnRotateRight.Clicked += new global::System.EventHandler (this.RotateRightButtonClicked);
			this.BtnFlip.Clicked += new global::System.EventHandler (this.FlipButtonClicked);
			this.BtnColorSelection.Clicked += new global::System.EventHandler (this.ColorSelectionButtonClicked);
			this.drawingarea.ExposeEvent += new global::Gtk.ExposeEventHandler (this.DrawingAreaExpose);
			this.drawingarea.DragDataReceived += new global::Gtk.DragDataReceivedHandler (this.DragData_Received);
			this.drawingarea.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.DrawingAreaClickReleased);
			this.BtnScrollLeft.Clicked += new global::System.EventHandler (this.ScrollLeftButtonClicked);
			this.iconview.DragDataGet += new global::Gtk.DragDataGetHandler (this.DragData_Get);
			this.iconview.DragBegin += new global::Gtk.DragBeginHandler (this.Drag_Begin);
			this.BtnScrollRight.Clicked += new global::System.EventHandler (this.ScrollRightButtonClicked);
		}
	}
}
